# https://github.com/matteyeux/ida-iboot-loader
UNIQUE_STR_XREFS = {
    "_do_printf": "<null>",
    "_platform_get_usb_serial_number_string": "CPID:",
    "_platform_get_usb_more_other_string": " NONC:",
    "_UpdateDeviceTree": "fuse-revision",
    "_main_task": "debug-uarts",
    "_platform_init_display": "backlight-level",
    "_do_memboot": "Combo image too large",
    "_do_go": "Memory image not valid",
    "_task_init": "idle task",
    "_sys_setup_default_environment": "/System/Library/Caches/com.apple.kernelcaches/kernelcache",
    "_check_autoboot": "aborting autoboot due to user intervention.",
    "_do_setpict": "picture too large: size:%zu",
    "_arm_exception_abort": "ARM %s abort at 0x%016llx:",
    "_do_devicetree": "Device Tree image not valid",
    "_do_ramdisk": "Ramdisk image not valid",
    "_nvme_bdev_create": "Couldn't construct blockdev for namespace %d",
    "_record_memory_range": "chosen/memory-map",
    "_boot_upgrade_system": "/boot/kernelcache",
    "_target_pass_boot_manifest": "chosen/manifest-properties",
    "_image4_validate_property_callback_interposer": "Unknown ASN1 type %llu",
    "_platform_handoff_update_devicetree": "iboot-handoff",
    "_prepare_and_jump": "======== End of %s serial output. ========",
}
